#!/bin/bash
## Author: 49 63 65 6d 61 6e (4963656d616e[AT]simfeni[DOT]com)
## VVJM

LEN=24
RND=/dev/urandom
#alpha=`echo {a..z} | tr -d ' '`
alpha="abcdefghjkmnpqrstuvwxyz"
#ALPHA=`echo {A..Z} | tr -d ' '`
ALPHA="ABCDEFGHJKLMNPQRSTUVWXYZ"
NUM=`echo {0..9} | tr -d ' '`
SYM="!@$%&(){}?"

## Tm90ZSAyOg==
while getopts "c:l:" opt; do
    case "${opt}" in
        c) args=$OPTARG ;;
        l) LEN=$OPTARG ;;
    esac
done

## Tm90ZSAzOg==
for i in $(seq 0 $(expr ${#args} - 1))
do
    init=${args:$i:1}
      if [ "$init" == "l" ]; then a=1
    elif [ "$init" == "u" ]; then b=3
    elif [ "$init" == "n" ]; then c=5
    elif [ "$init" == "s" ]; then d=11
      fi
done
sum=$((a + b + c + d))

## Tm90ZSA0Og==
if ( [[ "$sum" == "1" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | grep [$alpha] ) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$alpha" | head -c $LEN)
    done
echo -e $pass'\n'

## Tm90ZSA1Og==
elif ( [[ "$sum" == "3" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | grep [$ALPHA] ) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$ALPHA" | head -c $LEN)
    done
echo -e $pass'\n'

## Tm90ZSA2Og==
elif ( [[ "$sum" == "5" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | grep [$NUM] ) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$NUM" | head -c $LEN)
    done
echo -e $pass'\n'

## Tm90ZSA3Og==
elif ( [[ "$sum" == "11" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | grep [$SYM] ) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$SYM" | head -c $LEN)
    done
echo -e $pass'\n'

## Tm90ZSA4Og==
elif ( [[ "$sum" == "4" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | egrep ^[$alpha] | egrep [$alpha]{2} | egrep [$ALPHA]{3}) ]; do
        pass="$(cat $RND | LC_CTYPE=C tr -cd "$alpha$ALPHA" | head -c $LEN)"
    done
echo -e $pass'\n'

## Tm90ZSA5Og==
elif ( [[ "$sum" == "6" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | egrep ^[$alpha] | egrep [$alpha]{2} | egrep [$NUM]{3}) ]; do
        pass="$(cat $RND | LC_CTYPE=C tr -cd "$alpha$NUM" | head -c $LEN)"
    done
echo -e $pass'\n'

## Tm90ZSAxMDo=
elif ( [[ "$sum" == "8" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | egrep ^[$ALPHA] | egrep [$ALPHA]{2} | egrep [$NUM]{3}) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$ALPHA$NUM" | head -c $LEN)
    done
echo -e $pass'\n'

## Tm90ZSAxMTo=
elif ( [[ "$sum" == "12" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | egrep ^[$alpha] | egrep [$alpha]{2} | egrep [$SYM]{3}) ]; do
        pass="$(cat $RND | LC_CTYPE=C tr -cd "$alpha$SYM" | head -c $LEN)"
    done
echo -e $pass'\n'

## Tm90ZSAxMjo=
elif ( [[ "$sum" == "14" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | egrep ^[$ALPHA] | egrep [$ALPHA]{2} | egrep [$SYM]{3}) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$ALPHA$SYM" | head -c $LEN)
    done
echo -e $pass'\n'

## Tm90ZSAxMzo=
elif ( [[ "$sum" == "16" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | egrep [$NUM]{3} | egrep [$SYM]{3}) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$NUM$SYM" | head -c $LEN)
    done
echo -e $pass'\n'

## Tm90ZSAxNDo=
elif ( [[ "$sum" == "9" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | egrep ^[$alpha] | egrep [$alpha] | egrep [$ALPHA]{2} | egrep [$NUM]{2}) ]; do
        pass="$(cat $RND | LC_CTYPE=C tr -cd "$alpha$ALPHA$NUM" | head -c $LEN)"
    done
echo -e $pass'\n'

## Tm90ZSAxNTo=
elif ( [[ "$sum" == "15" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | egrep ^[$alpha] | egrep [$alpha] | egrep [$ALPHA]{2} | egrep [$SYM]{2}) ]; do
        pass="$(cat $RND | LC_CTYPE=C tr -cd "$alpha$ALPHA$SYM" | head -c $LEN)"
    done
echo -e $pass'\n'

## Tm90ZSAxNjo=
elif ( [[ "$sum" == "17" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | egrep ^[$alpha] | egrep [$alpha] | egrep [$NUM]{2} | egrep [$SYM]{2}) ]; do
        pass="$(cat $RND | LC_CTYPE=C tr -cd "$alpha$NUM$SYM" | head -c $LEN)"
    done
echo -e $pass'\n'

## Tm90ZSAxNzo=
elif ( [[ "$sum" == "19" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | egrep [$ALPHA]{2} | egrep [$NUM]{2} | egrep [$SYM]{2}) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$ALPHA$NUM$SYM" | head -c $LEN)
    done
echo -e $pass'\n'


## Tm90ZSAxODo=
elif ( [[ -z $args ]] || [[ "$sum" == "20" ]] && [[ "$LEN" -gt 11 && "$LEN" -lt 24 ]] ); then
    until [ $(echo $pass | egrep ^[$alpha] | egrep [$alpha] | egrep [$ALPHA]{2} | egrep [$NUM]{2} | egrep [$SYM]{3}) ]; do
        pass="$(cat $RND | LC_CTYPE=C tr -cd "$alpha$ALPHA$NUM$SYM" | head -c $LEN)"
    done
    echo -e $pass'\n';

elif ( [[ -z $args ]] || [[ "$sum" == "20" ]] && [[ "$LEN" -gt 23 ]] ); then
    until [ $(echo $pass | egrep ^[$alpha] | egrep [$alpha] | egrep [$ALPHA]{2} | egrep [$NUM]{2} | egrep [$SYM]{4}) ]; do
        pass="$(cat $RND | LC_CTYPE=C tr -cd "$alpha$ALPHA$NUM$SYM" | head -c $LEN)"
    done
    echo -e $pass'\n';

else
    echo -e "Length option (i.e. -l) MUST HAVE an argument greather than eleven (11)!\n"
fi
